# Generated by Django 5.0.1 on 2024-01-25 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id_acopio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cod_acopio', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cod_categoria_1', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_2', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_3', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_4', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_5', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_ciudad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '[transversal].[tblEkoAcopios]',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('compania', models.CharField(max_length=5)),
                ('cod_categoria_1', models.CharField(max_length=25)),
                ('cod_categoria_2', models.CharField(max_length=25)),
                ('cod_categoria_3', models.CharField(max_length=25)),
                ('cod_categoria_4', models.CharField(max_length=25)),
                ('cod_categoria_5', models.CharField(max_length=25)),
                ('cod_categoria_6', models.CharField(max_length=25)),
                ('cod_categoria_7', models.CharField(max_length=25)),
                ('cod_categoria_8', models.CharField(max_length=25)),
                ('cod_categoria_9', models.CharField(max_length=25)),
                ('cod_categoria_10', models.CharField(max_length=25)),
            ],
            options={
                'db_table': '[transversal].[tblEKOArticulo]',
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('localizacion', models.CharField(max_length=30)),
                ('compania', models.CharField(max_length=5)),
                ('fecha_actualizacion', models.DateField()),
                ('activa', models.BooleanField()),
            ],
            options={
                'db_table': '[transversal].[tblEKOLocalizaciones]',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cod_zona', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=100)),
                ('cod_categoria_1', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_2', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_3', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_4', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_5', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': '[recepcion].[tblEKOZonas]',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_fiscal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('compania', models.CharField(max_length=250)),
                ('razon_social', models.CharField(max_length=500)),
                ('nombre_comercial', models.CharField(max_length=500)),
                ('codigo_JDE', models.IntegerField()),
                ('codigo_siesa', models.IntegerField()),
                ('tipo_contribuyente', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=15)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('codigo_JDE_padre', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('cod_categoria_1', models.CharField(max_length=25)),
                ('cod_categoria_2', models.CharField(max_length=25)),
                ('cod_categoria_3', models.CharField(max_length=25)),
                ('cod_categoria_4', models.CharField(max_length=25)),
                ('cod_categoria_5', models.CharField(max_length=25)),
                ('cod_categoria_6', models.CharField(max_length=25)),
                ('cod_categoria_7', models.CharField(max_length=25)),
                ('cod_categoria_8', models.CharField(max_length=25)),
                ('cod_categoria_9', models.CharField(max_length=25)),
                ('cod_categoria_10', models.CharField(max_length=25)),
                ('activo', models.BooleanField()),
                ('id_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.acopio')),
            ],
            options={
                'db_table': '[transversal].[tblEkoProveedores]',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('proveedor_padre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('nombre_transportador', models.CharField(max_length=60)),
                ('nro_remision', models.CharField(max_length=20)),
                ('peso_remision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.FloatField()),
                ('fecha_validacion', models.DateField()),
                ('id_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.acopio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.proveedor')),
                ('cod_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.zona')),
            ],
            options={
                'db_table': '[recepcion].[tblEKOTickets]',
            },
        ),
        migrations.CreateModel(
            name='TicketDetalle',
            fields=[
                ('id_ticket_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_embalaje', models.CharField(max_length=20)),
                ('nro_tolva', models.CharField(max_length=10)),
                ('nro_precinto', models.IntegerField()),
                ('peso_bruto', models.FloatField()),
                ('Observacion_cambio_peso', models.CharField(max_length=100)),
                ('fecha_cambio_peso', models.DateField()),
                ('destare', models.FloatField()),
                ('peso_pnc', models.FloatField()),
                ('fecha_peso_pnc', models.DateField()),
                ('hora_inicial_seleccion', models.DateField()),
                ('hora_final_seleccion', models.DateField()),
                ('cod_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.articulo')),
                ('id_localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.localizacion')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.ticket')),
            ],
            options={
                'db_table': '[recepcion].[tblEKOTicketDetalle]',
            },
        ),
        migrations.CreateModel(
            name='TicketDetalleAdjunto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('archivo', models.CharField(max_length=500)),
                ('observacion', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('envio_correo', models.BooleanField()),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.ticketdetalle')),
            ],
            options={
                'db_table': '[recepcion].[tblEKOTicketDetalleAdjuntos]',
            },
        ),
    ]
