# Generated by Django 5.0.1 on 2024-01-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_acopio', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cod_categoria_1', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_2', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_3', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_4', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_categoria_5', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_ciudad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '[transversal].[tblEkoAcopios]',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_fiscal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('compania', models.CharField(max_length=250)),
                ('razon_social', models.CharField(max_length=500)),
                ('nombre_comercial', models.CharField(max_length=500)),
                ('codigo_JDE', models.IntegerField()),
                ('codigo_siesa', models.IntegerField()),
                ('tipo_contribuyente', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=15)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('codigo_JDE_padre', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('cod_categoria_1', models.CharField(max_length=25)),
                ('cod_categoria_2', models.CharField(max_length=25)),
                ('cod_categoria_3', models.CharField(max_length=25)),
                ('cod_categoria_4', models.CharField(max_length=25)),
                ('cod_categoria_5', models.CharField(max_length=25)),
                ('cod_categoria_6', models.CharField(max_length=25)),
                ('cod_categoria_7', models.CharField(max_length=25)),
                ('cod_categoria_8', models.CharField(max_length=25)),
                ('cod_categoria_9', models.CharField(max_length=25)),
                ('cod_categoria_10', models.CharField(max_length=25)),
                ('activo', models.BooleanField()),
                ('id_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.acopio')),
            ],
            options={
                'db_table': '[transversal].[tblEkoProveedores]',
            },
        ),
    ]
