# Generated by Django 5.0.1 on 2024-01-22 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEKOZona',
            fields=[
                ('cod_zona', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=100)),
                ('cod_categoria_1', models.CharField(max_length=25)),
                ('cod_categoria_2', models.CharField(max_length=25)),
                ('cod_categoria_3', models.CharField(max_length=25)),
                ('cod_categoria_4', models.CharField(max_length=25)),
                ('cod_categoria_5', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='tblEKOAcopios',
            new_name='tblEKOAcopio',
        ),
        migrations.CreateModel(
            name='tblEKOTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('proveedor_padre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('nombre_transportador', models.CharField(max_length=60)),
                ('nro_remision', models.CharField(max_length=20)),
                ('peso_remision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.FloatField()),
                ('fecha_validacion', models.DateField()),
                ('id_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.tblekoacopio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.tblekoproveedores')),
                ('usuario_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_tickets', to=settings.AUTH_USER_MODEL)),
                ('usuario_validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacion_tickets', to=settings.AUTH_USER_MODEL)),
                ('cod_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.tblekozona')),
            ],
        ),
    ]
