# Generated by Django 5.0.1 on 2024-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_tblekozona_rename_tblekoacopios_tblekoacopio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_5',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
