# Generated by Django 5.0.1 on 2024-01-25 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_rename_uuid_articulo_cod_articulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionBascula',
            fields=[
                ('consecutivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('usuario', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('verificacion', models.BooleanField()),
                ('observacion', models.CharField(max_length=1000)),
                ('dispositivo', models.CharField(max_length=50)),
                ('id_bascula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.configuracionbascula')),
            ],
            options={
                'db_table': '[bascula].[tblEKOVerificacionBasculas]',
            },
        ),
    ]
