# Generated by Django 5.0.1 on 2024-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_alter_tblekoacopio_cod_categoria_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekoacopio',
            name='cod_categoria_5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekozona',
            name='cod_categoria_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekozona',
            name='cod_categoria_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekozona',
            name='cod_categoria_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekozona',
            name='cod_categoria_4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblekozona',
            name='cod_categoria_5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
